version: '3.8'

services:
  backend:
    container_name: backend_container
    image: akshaymitra/movies_dashboard_backend
    # Uncomment the following lines to build the backend image locally
    # build:
    #   context: .
    #   dockerfile: backend/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network

  frontend:
    container_name: frontend_container
    image: akshaymitra/movies_dashboard_frontend
    depends_on:
      - backend
    # Uncomment the following lines to build the frontend image locally
    # build:
    #   context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
